CSS = r'''<style>
:root{--bg:#031426;--side:#08274a;--border:#1d5786;--text:#f7fbff;--muted:#b2c5d9;--input:#f3f6fa;--input-text:#142235}
[data-testid="stHeader"],[data-testid="stToolbar"],[data-testid="stDecoration"],[data-testid="stStatusWidget"],[data-testid="stSidebarCollapseButton"],[data-testid="collapsedControl"]{display:none!important;visibility:hidden!important}
html,body,[data-testid="stAppViewContainer"],.stApp{background:linear-gradient(180deg,#061d37 0%,#031426 48%,#020d1b 100%)!important;color:var(--text)!important}
.stAppViewContainer>.main{padding-top:0!important}.block-container{max-width:1900px;padding:.85rem 1.35rem 2rem!important}
[data-testid="stSidebar"]{display:block!important;visibility:visible!important;opacity:1!important;transform:translateX(0)!important;left:0!important;width:23rem!important;min-width:23rem!important;max-width:23rem!important;margin-left:0!important;background:linear-gradient(180deg,#0a315b,#061f3e)!important;border-right:1px solid #2470aa!important;box-shadow:8px 0 24px #0004!important}
[data-testid="stSidebar"]>div:first-child{display:block!important;visibility:visible!important;width:23rem!important;min-width:23rem!important;padding-top:1rem!important;background:linear-gradient(180deg,#0a315b,#061f3e)!important}
[data-testid="stSidebar"][aria-expanded="false"]{transform:translateX(0)!important;margin-left:0!important;visibility:visible!important}
[data-testid="stSidebar"] *{color:#eaf4ff!important}[data-testid="stSidebar"] [role="radiogroup"] label{min-height:2.4rem!important;padding:.5rem .65rem!important;border:1px solid transparent!important;border-radius:8px!important}[data-testid="stSidebar"] [role="radiogroup"] label:hover{background:#277ec53d!important;border-color:#51a0d859!important}
h1,h2,h3,h4,h5,h6{color:#fff!important}p,label,.stCaption,[data-testid="stCaptionContainer"]{color:var(--muted)!important}
[data-testid="stDateInput"] label,[data-testid="stSelectbox"] label,[data-testid="stNumberInput"] label{color:#e6f2ff!important;font-weight:650!important}
[data-baseweb="input"] input,[data-testid="stDateInput"] input{color:var(--input-text)!important;-webkit-text-fill-color:var(--input-text)!important}
[data-baseweb="select"]>div,[data-baseweb="input"]>div,[data-testid="stDateInput"]>div>div{color:var(--input-text)!important;background:var(--input)!important;border:1px solid #b9c8d7!important;border-radius:8px!important}
[data-baseweb="select"] span,[data-baseweb="select"] svg{color:var(--input-text)!important;fill:var(--input-text)!important}
[data-baseweb="popover"]>div,[role="listbox"],[role="option"],[data-baseweb="calendar"]{color:#eaf4ff!important;background:#0a2948!important}[data-baseweb="popover"] *,[role="listbox"] *,[role="option"] *,[data-baseweb="calendar"] *{color:#eaf4ff!important}[role="option"]:hover,[data-baseweb="calendar"] button:hover{background:#164c78!important}
.kpi{position:relative;overflow:hidden;min-height:136px;padding:14px;border:1px solid var(--border);border-radius:10px;background:linear-gradient(145deg,#0c3565,#09213f);box-shadow:0 8px 22px #0005;transition:transform .16s ease,box-shadow .16s ease}.kpi:hover{transform:translateY(-3px);box-shadow:0 13px 30px #0007}.kpi-positive{background:linear-gradient(145deg,#0c5a45,#0a333c 55%,#09213f)!important;border-color:#2fd18e!important}.kpi-negative{background:linear-gradient(145deg,#65253a,#351f36 55%,#09213f)!important;border-color:#ef6a82!important}.kpi-warning{background:linear-gradient(145deg,#67451b,#382e25 55%,#09213f)!important;border-color:#e7a23d!important}.kpi-plan{background:linear-gradient(145deg,#49347a,#292750 55%,#09213f)!important;border-color:#9d87e3!important}.kpi-neutral{background:linear-gradient(145deg,#0c3565,#09213f)!important}.kt{color:#eaf4ff;font-size:.72rem;font-weight:800;line-height:1.3;text-transform:uppercase}.kv{color:#fff;font-size:1.55rem;font-weight:800;margin:10px 0 7px}.ks{color:#c5d7e8;font-size:.68rem;line-height:1.45}.asof{display:inline-block;padding:7px 12px;border:1px solid #3787bf;border-radius:8px;color:#fff;background:#09213f;font-weight:750}
[data-testid="stDataFrame"]{overflow:hidden!important;background:#071c34!important;border:1px solid #245d89!important;border-radius:9px!important}[data-testid="stDataFrame"]>div,[data-testid="stDataFrame"] canvas{background:#071c34!important}[data-testid="stElementToolbar"]{color:#eaf4ff!important;background:#0a294a!important}
.stDownloadButton>button,.stButton>button{color:#fff!important;background:linear-gradient(135deg,#1468b8,#0c4c91)!important;border:1px solid #3b91d2!important;border-radius:8px!important;font-weight:700!important}[data-testid="stAlert"]{color:#edf7ff!important;background:#0a2948!important;border:1px solid #2b6f9f!important;border-radius:8px!important}[data-testid="stAlert"] *{color:#edf7ff!important}
</style>'''
